---
title: "Práctico clase 2 - Puliendo gráficos para publicar"
author: 
  - Diplomatura en Ciencias Sociales Computacionales
  - Seminario de Visualización de datos en R
  - Florencia Piñeyrúa, Santiago Nuñez y Nayla Sol Garcilazzo
date: '2024-05-14'
output: html_document
---
## Práctico 2

Usando *ggplot2*, vamos a seguir jugando con gapminder. Esta vez, vamos a explorar la relación entre la tasa de fertilidad, la expectativa de vida y el tamaño de la población. 

Primero, importamos las librerías `ggplot` y `dplyr`. Segundo, vamos a leer el archivo `gapminder_clean.csv` que está en la carpeta `data`. 

## Ejercicio 1

Realizá un gráfico que muestre la relación entre la tasa de fertilidad y la expectativa de vida en el año 2007 para todos los países. 

## Ejercicio 2

Introducí en el gráfico las variables de `continent` y `pop` (tamaño de la población). Pensá: ¿qué atributos estéticos puedo utilizar para mostrar los valores según el tipo de variable? Luego ploteá un gráfico de muestra.


## Ejercicio 3

Modificá manualmente los colores de los continentes. Queremos que Europa tenga el tono "darkorange", Asia "red", África "blue", las Américas "yellow" y Oceanía "purple". 


¿Y si quisiera mostrar dónde están Arg y Brasil en este gráfico?

## Ejercicio 4

Realizá limpieza y ordenamiento finales, asegurate de que las labels describan debidamente su elemento asignado. 

¿Cómo guardo los gráficos? Uso `ggsave()` .

Recuerden que por default me guarda el último plot hecho, si lo quiero cambiar, modifico el parámetro `plot`. PERO para eso tengo que haberlo guardado en un objeto primero. 

